services:
  - type: worker
    name: udemy-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_worker.py

  - type: web
    name: udemy-bot-health
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python health_server.py
    plan: free
